// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjlilpfadpoxbowgcbml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqbGlscGZhZHBveGJvd2djYm1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MTgyNTYsImV4cCI6MjA1NjA5NDI1Nn0.0tCDVvhJHF6704pC9RMcYFHjbAI1XalMIjdzF5y0VZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);